const data = {
  products: [
    {
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidake",
      rating: 4.5,
      numReviews: 4,
      countInStock: 30,
      description: "A popular shirt",
    },
    {
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 80,
      brand: "raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pant",
      category: "Pants",
      slug: "golf-pants",
      image: "/images/pants1.jpg",
      price: 60,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking Pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",

      category: "Pants",
      image: "/images/pants2.jpg",
      price: 90,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smat pants",
    },
    {
      name: "Clasic Pants",
      category: "Pants",
      slug: "free-pants",

      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casley",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smat pants",
    },
  ],
};

export default data;
